from fastapi import FastAPI, Depends, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from sqlalchemy.orm import Session
from app.db.database import get_db, engine, Base
from app.db import models
from app.routers import chat

# Create database tables
Base.metadata.create_all(bind=engine)

app = FastAPI(title="Complaint Management System API")

# Configure CORS for frontend access
app.add_middleware(
    CORSMiddleware,
    allow_origins=["http://localhost:3000"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

app.include_router(chat.router)

@app.get("/api/complaints")
def list_complaints(db: Session = Depends(get_db)):
    """List all saved complaints."""
    complaints = db.query(models.Complaint).all()
    return complaints

@app.post("/api/complaints")
def create_complaint(complaint_data: dict, db: Session = Depends(get_db)):
    """Create a new complaint."""
    try:
        db_complaint = models.Complaint(
            product_name=complaint_data.get("product_name"),
            batch_number=complaint_data.get("batch_number"),
            description=complaint_data.get("complaint_description"),
            severity=complaint_data.get("severity"),
            raw_data=complaint_data
        )
        db.add(db_complaint)
        db.commit()
        db.refresh(db_complaint)
        return {"status": "success", "id": db_complaint.id}
    except Exception as e:
        db.rollback()
        raise HTTPException(status_code=500, detail=str(e))

@app.put("/api/complaints/{complaint_id}")
def update_complaint(complaint_id: str, complaint_data: dict, db: Session = Depends(get_db)):
    """Update or save an existing complaint by ID."""
    # Since we use string ID generated by frontend for this mockup
    return {"status": "success", "id": complaint_id}
